generic:
  image: nabs/nabs:v1
  environment:
    DOMAINE_NAME: ${DOMAINE_NAME}
    SITE_DB_NAME: ${MYSQL_DATABASE}
    SITE_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
    SITE_DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  external_links:
    - galera/galera-lb:mysql
    - memcached/memcache:mcserver
  volumes:
    - ${VOLUME_IMG}:/var/www/html/IMG
    - ${VOLUME_LIB}:/var/www/html/lib
  tty: true
  stdin_open: true
  volume_driver: ${VOLUME_DRIVER}
  labels:
    io.rancher.container.pull_image: "always"
    io.rancher.scheduler.global: "true"
    io.rancher.scheduler.affinity:host_label: "trefle=1"
