version: '2'
services:
  generic:
    image: registry.idcalg.com:5000/idc/generic:v0.2
    environment:
      SVN_REPOSITORY: ${SVN_REPOSITORY}
      DATA_VOLUME: ${MYSQL_DATABASE}
      DOMAINE_NAME: ${DOMAINE_NAME}
      SITE_DB_NAME: ${MYSQL_DATABASE}
      SITE_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
      SITE_DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SITE_DEPLOYMENT: ${SITE_DEPLOYMENT}
      TIME_ZONE: ${TIME_ZONE}
    stdin_open: true
    external_links:
    - galera/galera-lb:mysql
    - backup/backup:bc
    volumes:
    - /data/${MYSQL_DATABASE}_IMG:/var/www/html/IMG
    tty: true
    volume_driver: ${VOLUME_DRIVER}
    labels:
      io.rancher.container.pull_image: "always"
      io.rancher.scheduler.global: "true"
      io.rancher.scheduler.affinity:host_label: "appli=1"
      urlsite: ${DOMAINE_NAME}
