.catalog:
  name: "Generic"
  version: "Generic-V0.1"
  description: "Site de base"
  maintainer: "Nabil DJIDI <public@djidi.com>"
  uuid: generic-0
  questions:
    - variable: "DOMAINE_NAME"
      label: "Nom de domaine"
      description: "Nom de domaine du site"
      type: "string"
      required: true
    - variable: "MYSQL_ROOT_PASSWORD"
      label: "Mot de passe MYSQL"
      description: "Mot de passe administrateur Mysql (root)"
      type: "string"
      required: true
    - variable: "MYSQL_DATABASE"
      label: "Base MYSQL"
      description: "Nom de la base de donnee Mysql"
      type: "string"
      required: true
    - variable: "MYSQL_DB_PASSWORD"
      label: "Mot de passe app MYSQL"
      description: "Mot de passe de la base de donnee Mysql"
      type: "string"
      required: true
    - variable: "VOLUME_IMG"
      label: "Volume IMG"
      description: "Chemin du volume IMG"
      type: "string"
      required: false
    - variable: "VOLUME_LIB"
      label: "Volume lib"
      description: "Chemin du volume lib"
      type: "string"
      required: false
    - variable: "VOLUME_DRIVER"
      label: "DRIVER Volume"
      description: "Driver a utiliser pour monter le volume (ex:convoy)"
      type: "string"
      required: false
      default: "convoy-nfs"

composer:
