.catalog:
  name: "Generic"
  version: "Generic-V0.2"
  description: "Site de base ubuntu"
  maintainer: "Nabil DJIDI <public@djidi.com>"
  uuid: generic-0
  questions:
    - variable: "DOMAINE_NAME"
      label: "Nom de domaine"
      description: "Nom de domaine du site"
      type: "string"
      required: true
    - variable: "MYSQL_ROOT_PASSWORD"
      label: "Mot de passe MYSQL"
      description: "Mot de passe administrateur Mysql (root)"
      type: "string"
      required: true
    - variable: "MYSQL_DATABASE"
      label: "Base MYSQL"
      description: "Nom de la base de donnee Mysql"
      type: "string"
      required: true
    - variable: "MYSQL_DB_PASSWORD"
      label: "Mot de passe app MYSQL"
      description: "Mot de passe de la base de donnee Mysql"
      type: "string"
      required: true
    - variable: "VOLUME"
      label: "Prefix du Volume"
      description: "Préfix des volumes IMG (nom des repertoires dans sur le serveur nfs: prefix_IMG, prfix_local, prefix_tmp)"
      type: "string"
      required: false
    - variable: "VOLUME_DRIVER"
      label: "DRIVER Volume"
      description: "Driver a utiliser pour monter le volume (ex:convoy)"
      type: "string"
      required: false
      default: "convoy-nfs"

composer:
