plex:
  image: timhaak/plex
  environment:
    TZ: Europe/Paris
    VERSION: latest
    PLEX_TOKEN: ${PLEX_TOCKEN}
  stdin_open: true
  volumes:
    - ${VOLUME}/config:/config
    - ${VOLUME}/data:/data
    - ${VOLUME}/transcode:/transcode
  tty: true
  labels:
    io.rancher.scheduler.affinity:host_label: plex=1
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
deluge:
  image: linuxserver/deluge
  environment:
    TZ: Europe/Paris
  stdin_open: true
  network_mode: host
  volumes:
  - ${VOLUME}/data:/downloads
  - /deluge/config:/config
  tty: true
  labels:
    io.rancher.scheduler.affinity:host_label: plex=1
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
