backup:
  image: nabs/backup
  environment:
    MYSQL_HOST: ${MYSQL_HOST}
    MYSQL_PORT: ${MYSQL_PORT}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASS: ${MYSQL_PASS}
    FTP_DEV_HOST: ${FTP_DEV_HOST}
    FTP_DEV_PORT: ${FTP_DEV_PORT}
    FTP_DEV_USER: ${FTP_DEV_USER}
    FTP_DEV_PASS: ${FTP_DEV_PASS}
    FTP_HOST: ${FTP_HOST}
    FTP_PORT: ${FTP_PORT}
    FTP_USER: ${FTP_USER}
    FTP_PASS: ${FTP_PASS}
    FTP_DIRECTORY: ${FTP_DIRECTORY}
    HOST_FOLDER: ${HOST_FOLDER}
    CRON_TIME: ${CRON_TIME}
    MAX_BACKUPS: ${MAX_BACKUPS}
    INIT_BACKUP: ${INIT_BACKUP}
  external_links:
  - galera/galera-lb:mysql
  volumes:
  - ${HOST_FOLDER}:/exports
  - /var/run/docker.sock:/tmp/docker.sock:ro
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.pull_image: "always"
    io.rancher.scheduler.global: "true"
    io.rancher.scheduler.affinity:host_label: "appli=1"
