.catalog:
  name: "backup"
  version: "Backup-V0.3"
  description: "Backup to FTP"
  maintainer: "IDC"
  uuid: backup-0
  questions:
    - variable: "MYSQL_HOST"
      label: "Hote MYSQL"
      description: "Hote serveur Mysql (auto link:mysql)"
      type: "string"
      required: true
      default: "mysql"
    - variable: "MYSQL_PORT"
      label: "port MYSQL"
      description: "Port serveur Mysql"
      type: "string"
      required: true
      default: "3306"
    - variable: "MYSQL_USER"
      label: "Utilsateur MYSQL"
      description: "Utilisateur Mysql"
      type: "string"
      required: true
      default: "root"
    - variable: "MYSQL_PASS"
      label: "Mot de passe MYSQL"
      description: "Mot de passe Mysql"
      type: "string"
      required: true
    - variable: "FTP_HOST"
      label: "Hote FTP de backup"
      description: "Hote serveur FTP de backup"
      type: "string"
      required: true
      default: "dedibackup-dc2.online.net"
    - variable: "FTP_PORT"
      label: "port FTP de backup"
      description: "Port serveur FTP de backup"
      type: "string"
      required: true
      default: "21"
    - variable: "FTP_USER"
      label: "Utilsateur FTP de backup"
      description: "Utilisateur FTP de backup"
      type: "string"
      required: true
      default: "auto"
    - variable: "FTP_PASS"
      label: "Mot de passe FTP de backup"
      description: "Mot de passe FTP"
      type: "string"
      required: true
      default: "auto"
    - variable: "FTP_DIRECTORY"
      label: "Repertoire FTP"
      description: "Repertoire de destination FTP"
      type: "string"
      required: true
      default: "/"
    - variable: "FTP_DEV_HOST"
      label: "Hote FTP de deploiement"
      description: "Hote serveur FTP de deploiement"
      type: "string"
      default: ""
    - variable: "FTP_DEV_PORT"
      label: "port FTP Developpement de deploiement"
      description: "Port serveur FTP de deploiement"
      type: "string"
      default: "21"
    - variable: "FTP_DEV_USER"
      label: "Utilsateur FTP de deploiement"
      description: "Utilisateur FTP de deploiement"
      type: "string"
      default: "transfer"
    - variable: "FTP_DEV_PASS"
      label: "Mot de passe FTP de deploiement"
      description: "Mot de passe FTP de deploiement"
      type: "string"
    - variable: "HOST_FOLDER"
      label: "Repertoire à sauvegarder sur le host"
      description: "Localisation du repertoire sur le host qui contient les données (ex:/data | /exports)"
      type: "string"
      required: true
      default: "/data"
    - variable: "CRON_TIME"
      label: "Tache Cron"
      description: "Evenement Cron (ex:0 0 * * *)"
      type: "string"
      required: true
      default: "0 0 * * *"
    - variable: "MAX_BACKUPS"
      label: "Nombre de backup"
      description: "Nombre de Backup"
      type: "string"
      required: true
      default: "3"
    - variable: "INIT_BACKUP"
      label: "Lancement au demarrage"
      description: "Lancer au demarrage du container ? (oui ou vide)"
      type: "string"
      default: "oui"

backup:
