.catalog:
  name: "Galera DB"
  version: 10.0.22-rancher1
  description: |
    Galera Cluster based on MariaDB 10.0.22 + phpmyadmin
  questions:
    - variable: "mysql_data"
      label: "Répertoire de Données"
      description: "Localisation du répertoire de donnée sur le serveur host (Ex:/data/mysql)"
      type: "string"
      default: "/data/mysql"
      required: true
    - variable: "mysql_root_password"
      type: string
      required: true
      label: "MySQL Root Password"
      description: "Password given to the root mysql user"
galera:
  scale: 3
  metadata:
    mysqld: |
      innodb_file_per_table = 1
      innodb_autoinc_lock_mode=2
      query_cache_size=0
      query_cache_type=0
      innodb_flush_log_at_trx_commit=0
      binlog_format=ROW
      default-storage-engine=innodb
      wsrep_provider=/usr/lib/galera/libgalera_smm.so
      wsrep_provider_options="gcache.size = 2G"
      wsrep_sst_method=mysqldump
      wsrep_sst_auth=root:${mysql_root_password}
      progress=1
galera-lb:
  scale: 1
  load_balancer_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
PhpMyAdmin:
  health_check:
      port: 80
      interval: 10000
      unhealthy_threshold: 3
      request_line: GET / HTTP/1.0
      healthy_threshold: 2
      response_timeout: 10000
